repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      # Go Build
      -   id: go-build-repo-mod
      # Go Mod Tidy
      -   id: go-mod-tidy-repo
      # Go Vet
      -   id: go-vet-repo-mod
      # Style
      -   id: go-imports-repo
      # -   id: golangci-lint-repo-mod
      #     args: [-E,whitespace,-E,gocritic,-E,revive,-E,gosec,--timeout,5m]
      # Go Test
      -   id: go-test-mod
      -   id: go-test-repo-mod
